### PR TITLE
feat:select nearest diagnostic

### PR DESCRIPTION
**Pull request by smoka7**

### CODE REVIEW

**Comment by andrewferrier** [comment]
Hi - thanks for the pull request. I don't really understand exactly what it's doing though - can you explain please?

**Comment by smoka7** [comment]
It selects diagnostic under the cursor and if  the cursor isn't under any diagnostic selects the closest one

**Comment by andrewferrier** [comment]
Hmm - so this is bidirectional?

Can you give me a usecase for this? Is this something you think folks will use?

I do already want to take a look if it's possible to simplify or refactor the current `next_diag_inclusive()` function. I'll look at this in that context.

Thanks!

**Comment by smoka7** [comment]
Yes its bidirectional.
use case: you're on the same line as diagnostic and you don't know wheatear your cursor is before, under or after diagnostic.with this function you can select it without using any other motion.

**Comment by smoka7** [comment]
I tried to change the `next_diag_inclusive()` 
```
M.next_diag_inclusive = function(local_opts)
	local cursor = vim.api.nvim_win_get_cursor(0)
	local current_line = cursor[1] - 1
	local current_column = cursor[2]

	local next = vim.diagnostic.get_next({ cursor_position = { current_line, current_column } })
	local prev = vim.diagnostic.get_prev({ cursor_position = { current_line, current_column } })
	vim.pretty_print(current_line, current_column, prev, next)
	local closest = next
	if
		(current_line >= prev.lnum and current_line <= prev.end_lnum)
		and (current_column >= prev.col and current_column <= prev.end_col)
	then
		closest = prev
	end
	if closest ~= nil then
		select_diagnostic(closest)
	end
end
```
but it doesn't select the next diagnostic when cursor is on a same line with a diagnostic.

**Comment by andrewferrier** [comment]
So thinking about this - I don't think I want to change the behaviour of `next_diag_inclusive()` (although simplifying/refactoring the implementation would be welcome if possible). But most folks I believe are wanting text objects which look ahead, even if there is a closer one behind (see all the inbuilt NeoVim text objects for an example).

I am open to including this as a separate function which is not keymapped by default but can be bound by the user if they wish. However, currently this is failing some automated tests which I have written for it. I'll take a look later to see if I can find out what's wrong.

```
    it("can change nearest diagnostic - row 1", function()
        vim.api.nvim_win_set_cursor(0, { 1, 0 })
        vim.cmd("normal cnghello")
        check_lines({
            "test1",
            "hello",
            "test3",
            "test4",
            "test5",
        })
    end)

    it("can change nearest diagnostic - row 2", function()
        vim.api.nvim_win_set_cursor(0, { 2, 0 })
        vim.cmd("normal cnghello")
        check_lines({
            "test1",
            "hello",
            "test3",
            "test4",
            "test5",
        })
    end)

    it("can change nearest diagnostic - row 3", function()
        vim.api.nvim_win_set_cursor(0, { 2, 0 })
        vim.cmd("normal cnghello")
        check_lines({
            "test1",
            "test2",
            "hello",
            "test4",
            "test5",
        })
    end)
```

**Comment by smoka7** [comment]
Sorry, I messed up the git history.
The third test you mentioned just had a typo. I added some test for the function and they're passing.
I added the mapping just for the tests, if you don't want to map it by default; I can remove it.

**Comment by smoka7** [comment]
okay I will test them.

**Comment by smoka7** [comment]
Both functions now are passing the tests.

**Comment by andrewferrier** [comment]
Thanks for this! For now, I have decided to stick with the previous implementation of `next_diag_inclusive()`, as I find it clearer to understand/maintain - and theoretically it should be faster in performance too, since it only has to iterate the diagnostic list once, although this isn't the main consideration.

But I've merged `nearest_diag()`, and made that something the user can set up their own keybinding for. It seems to work well, thank you for the contribution!

**Pull request merged**
